# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      
      - name: Listar carpetas
        run: |
          echo "Listando repositorios"
          ls -la

          echo "Mostrando carpeta actual"
          pwd

      # Configure Java Version 17
      - name: Set Java JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: "maven"

      # Build with Maven
      - name: Build with Maven
        run: mvn -B clean verify


      - name: SonarCloud Analysis with Maven Plugin 
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \ 
          -Dsonar.projectKey=${{ secrets.SONAR_KEY }} \ 
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \ 
          -Dsonar.projectName="JUnit Basic" \ 
          -Dsonar.host.url=https://sonarcloud.io \ 
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
      #     echo "Mostrar mi variable ${{ vars.MY_VARIABLE }}"
      #     echo "Repository: ${{ github.repository }}"


     # - name: Official SonarQube Scan
     #   uses: SonarSource/sonarqube-scan-action@v6.0.0
     #   env:
     #      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
     #   with:
     #     args: >
     #       -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
     #       -Dsonar.projectKey=${{ secrets.SONAR_KEY }}
     #       -Dsonar.java.binaries=target/classes
       
